name = "SurrealNumbers"
uuid = "58abba7c-3f8b-5571-af36-87c463197a71"
authors = ["Matthew Roughan <matthew.roughan@adelaide.edu.au>"]
version = "0.2.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"

[compat]
julia = "1.10"
DataStructures = "0.18"

